# Generated by Django 5.2 on 2026-03-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['po_date'], name='portal_purc_po_date_b161d4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['store', 'po_date'], name='portal_purc_store_i_a74979_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['product', 'po_date'], name='portal_purc_product_71b9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['vendor', 'po_date'], name='portal_purc_vendor__0ac9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sales_date'], name='portal_sale_sales_d_46fccb_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'sales_date'], name='portal_sale_store_i_4bb46b_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['product', 'sales_date'], name='portal_sale_product_8b026e_idx'),
        ),
    ]
