# Generated by Django 5.2 on 2026-03-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_purchase_portal_purc_po_date_b161d4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('vendor_id', models.IntegerField()),
                ('vendor_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_qty_bought', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'month'], name='portal_purc_year_2c6354_idx'), models.Index(fields=['store_id', 'year', 'month'], name='portal_purc_store_i_ab82bc_idx'), models.Index(fields=['city', 'year', 'month'], name='portal_purc_city_b13eba_idx')],
            },
        ),
        migrations.CreateModel(
            name='SaleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('vendor_id', models.IntegerField()),
                ('vendor_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_qty_sold', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'month'], name='portal_sale_year_3d7dd3_idx'), models.Index(fields=['store_id', 'year', 'month'], name='portal_sale_store_i_53fbb2_idx'), models.Index(fields=['city', 'year', 'month'], name='portal_sale_city_36287b_idx')],
            },
        ),
    ]
