services:
  db:
    image: postgres:16
    container_name: annie_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./backend
    container_name: annie_web
    # DEVELOPMENT
    # command: python manage.py runserver 0.0.0.0:8000
    # PRODUCTION
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2
    volumes:
      - ./backend:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: